package io.kestra.plugin.argocd.apps;

import io.kestra.core.junit.annotations.KestraTest;
import io.kestra.core.models.property.Property;
import io.kestra.core.runners.RunContext;
import io.kestra.core.runners.RunContextFactory;
import io.kestra.core.utils.TestsUtils;
import io.kestra.plugin.scripts.runner.docker.Docker;
import jakarta.inject.Inject;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@KestraTest
class ArgoCDTasksIntegrationTest {
    private static final Path SETUP_ENV_FILE = Path.of("/tmp/plugin-argocd-ci/setup.env");
    private static final String SERVER_KEY = "ARGOCD_TEST_SERVER";
    private static final String APP_KEY = "ARGOCD_TEST_APP";
    private static final String TOKEN_FILE_KEY = "ARGOCD_TEST_TOKEN_FILE";
    private static final Set<String> EXPECTED_HEALTH_STATES = Set.of("Healthy", "Progressing", "Unknown");

    private static String argocdServer;
    private static String argocdApplication;
    private static String argocdToken;

    @Inject
    private RunContextFactory runContextFactory;

    @BeforeAll
    static void initArgoCDContext() throws Exception {
        Assumptions.assumeTrue(Files.exists(SETUP_ENV_FILE), "Missing ArgoCD setup file. Run .github/setup-unit.sh before integration tests.");

        var setupValues = parseSetupFile();
        argocdServer = requireSetupValue(setupValues, SERVER_KEY);
        argocdApplication = requireSetupValue(setupValues, APP_KEY);

        var tokenFile = Path.of(requireSetupValue(setupValues, TOKEN_FILE_KEY));
        Assumptions.assumeTrue(Files.exists(tokenFile), "Missing ArgoCD token file generated by setup script.");

        argocdToken = Files.readString(tokenFile).trim();
        Assumptions.assumeFalse(argocdToken.isBlank(), "ArgoCD token generated by setup script is empty.");
    }

    @Test
    void shouldSyncAndGetStatusFromRealArgoCDApp() throws Exception {
        var sync = Sync.builder()
            .id("sync")
            .type(Sync.class.getName())
            .build();
        configureCommon(sync);

        var syncOutput = sync.run(runContext(sync));
        assertEquals(0, syncOutput.getExitCode());
        assertEquals("Synced", syncOutput.getSyncStatus());
        assertNotNull(syncOutput.getRawOutput());
        assertFalse(syncOutput.getRawOutput().isBlank());

        var status = Status.builder()
            .id("status")
            .type(Status.class.getName())
            .build();
        configureCommon(status);

        Status.Output statusOutput = null;
        for (var attempt = 0; attempt < 10; attempt++) {
            statusOutput = status.run(runContext(status));
            if ("Synced".equals(statusOutput.getSyncStatus()) && EXPECTED_HEALTH_STATES.contains(statusOutput.getHealthStatus())) {
                break;
            }
            Thread.sleep(2_000L);
        }

        assertNotNull(statusOutput);
        assertEquals(0, statusOutput.getExitCode());
        assertEquals("Synced", statusOutput.getSyncStatus());
        assertTrue(EXPECTED_HEALTH_STATES.contains(statusOutput.getHealthStatus()));
        assertNotNull(statusOutput.getResources());
    }

    private static Map<String, String> parseSetupFile() throws Exception {
        var setupValues = new HashMap<String, String>();
        for (var line : Files.readAllLines(SETUP_ENV_FILE)) {
            var trimmed = line.trim();
            if (trimmed.isBlank() || trimmed.startsWith("#")) {
                continue;
            }

            var separatorIndex = trimmed.indexOf('=');
            if (separatorIndex <= 0) {
                continue;
            }

            var key = trimmed.substring(0, separatorIndex);
            var value = trimmed.substring(separatorIndex + 1);
            setupValues.put(key, value);
        }

        return setupValues;
    }

    private static String requireSetupValue(Map<String, String> setupValues, String key) {
        var value = setupValues.get(key);
        assertNotNull(value, "Missing required setup value: " + key);
        assertFalse(value.isBlank(), "Setup value is empty: " + key);
        return value;
    }

    private static void configureCommon(AbstractArgoCD task) {
        task.server = Property.ofValue(argocdServer);
        task.token = Property.ofValue(argocdToken);
        task.application = Property.ofValue(argocdApplication);
        task.insecure = Property.ofValue(true);
        task.taskRunner = Docker.builder()
            .type(Docker.class.getName())
            .networkMode("host")
            .build();
    }

    private RunContext runContext(AbstractArgoCD task) {
        return TestsUtils.mockRunContext(
            runContextFactory,
            task,
            Map.of(
                "flow", Map.of(
                "id", "flow",
                "namespace", "io.kestra.test",
                "tenantId", "main")
        ));
    }
}
